language: csharp
solution: CoreZipCode.sln
mono: none
dotnet: 2.0
script:
 - dotnet restore
install:
  - nuget restore CoreZipCode.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release CoreZipCode.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./CoreZipCode.Tests/bin/Release/CoreZipCode.Tests.dll