language: csharp
mono: none
sudo: required
dist: xenial
dotnet: 2.2

install:
  - dotnet tool install -g coveralls.net --version 1.0.0
  - dotnet restore

script:
  - dotnet build
  - dotnet test CoreZipCode.Tests/CoreZipCode.Tests.csproj -p:CollectCoverage=true -p:CoverletOutputFormat=opencover -p:CoverletOutput=".coverage/coverage.opencover.xml"  -p:Exclude="[CoreZipCode.Tests*]*" -p:Exclude="[xunit*]*" -p:ExcludeByFile="../CoreZipCode/Services/ViaCep.cs"
  - echo $TRAVIS_JOB_ID
  - $HOME/.dotnet/tools/csmacnz.Coveralls -i CoreZipCode.Tests/.coverage/coverage.opencover.xml --opencover --repoToken $COVERALLS_REPO_TOKEN --jobId $TRAVIS_JOB_ID --serviceName "travis-ci" --useRelativePaths

branches:
  only:
    - master
    - develop

deploy:
  provider: script
  script: chmod +x .deploy/deploy.sh && .deploy/deploy.sh $NUGET_API_KEY $TRAVIS_TAG
  skip_cleanup: true
  on:
    tags: true
